version: "3.3"
services:
  datagear:
    build:
      context: ./ #Dockerfile的目录
    network_mode: host
    restart: always
    container_name: datagear
    image: datagear
    privileged: true #容器内root等同于宿主机root
    ports:
      - 50401:50401
    volumes: #如果上传文件保存在本地需要进行地址映射
      - /data/volumes/java/logs/datagear:/java/log
      - /data/volumes/java/tmp/datagear:/java/tmp