version: '2'
services:
  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      TZ: Asia/Shanghai
      ES_JAVA_OPTS: -Xms512m -Xmx512m #设置使用jvm内存大小
    volumes:
      - ./volumes/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载!!!需要创建目录并且授予写入执行权限 chmod 777 [目录]
      - ./volumes/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml #配置文件挂载
  kibana:
    image: kibana:7.7.0
    container_name: kibana
    # restart: always
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200 #设置访问elasticsearch的地址
    volumes:
      - ./volumes/kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
  logstash:
    image: logstash:7.7.0
    container_name: logstash
    # restart: always
    volumes:
      - ./volumes/logstash/conf/logstash-springboot.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
      - ./volumes/logstash/conf/logstash.yml:/usr/share/logstash/config/logstash.yml #挂载logstash的配置文件
    depends_on:
      - elasticsearch #logstash在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - 4560:4560
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.0
    container_name: filebeat
    hostname: filebeat
    # restart: always
    volumes:
      - ./volumes/filebeat/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /data/logs/point/all/:/logs/point/
    depends_on:
      - logstash
    ports:
      - 5044:5044
  oap:
    image: apache/skywalking-oap-server:8.8.0
    container_name: skywalking-oap
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:es
    # restart: always
    ports:
      - 1234:1234
      - 11800:11800
      - 12800:12800
    environment:
      TZ: Asia/Shanghai
      SW_STORAGE: elasticsearch7
      SW_STORAGE_ES_CLUSTER_NODES: es:9200
      SW_ES_USER: elastic #es的账号
      SW_ES_PASSWORD: admin123 #es的密码
  ui:
    image: apache/skywalking-ui:8.8.0
    container_name: skywalking-ui
    depends_on:
      - oap
    links:
      - oap
    # restart: always
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Shanghai 
      SW_OAP_ADDRESS: oap:12800
      security.user.admin.password: admin123
