version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - /data/volumes/wordpress/mysql:/var/lib/mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: F72UDgtg2HdJ82T1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "9909:80"
    restart: always
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /data/volumes/wordpress/html:/var/www/html