version: '3.3'
services:
  frps:
    image: snowdreamtech/frps
    restart: always
    container_name: frps
    network_mode: host #直接跟宿主机共用网络
    privileged: true #容器内root等同于宿主机root
    volumes:
      - /data/volumes/frps.ini:/etc/frp/frps.ini
      - /etc/localtime:/etc/localtime:ro
