version: "3.3"
services:
  java:
    build:
      context: ./ #Dockerfile的目录
    network_mode: host
    restart: always
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE}
    privileged: true #容器内root等同于宿主机root
    ports:
      - ${PORTS}:8080
    volumes: #如果上传文件保存在本地需要进行地址映射
      - /data/java/yuqing/logs/${CONTAINER_NAME}:/java/logs
      - /data/java/yuqing/tmp/${CONTAINER_NAME}:/java/tmp
      - /data/java/yuqing/config/${CONTAINER_NAME}:/java/config
    #  - /data/volumes/java/config/${CONTAINER_NAME}:/java/config  #springboot外部注入配置文件目录
    env_file: .env
    # 设置系统代理
    #environment:
    #  - "http_proxy=http://squid:squid@43.138.255.110:3128"
    #  - "https_proxy=http://squid:squid@43.138.255.110:3128"
    #  - "no_proxy=localhost,127.0.0.1,43.143.56.113,43.138.255.110"
    #networks:
    #  - vlan-mysql
    #  - vlan-redis
#networks:
#  vlan-mysql:
#    external: true
#  vlan-redis:
#    external: true