version: "3"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    env_file:
      - ./env/nacos-standlone-mysql.env
    networks:
      - vlan-nacos
      - vlan-mysql
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
      # - ./conf/application.properties:/home/nacos/conf/application.properties:ro
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    restart: always
networks:
  vlan-nacos:
    external: true
  vlan-mysql:
    external: true