version: "3"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    networks:
      - vlan-nacos
      - vlan-mysql
    volumes:
      - ./volumes/nacos/logs/:/home/nacos/logs
      - ./volumes/conf/custom.properties:/home/nacos/init.d/custom.properties
      - ./volumes/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    restart: always
networks:
  vlan-nacos:
    external: true
  vlan-mysql:
    external: true
