version: "3"
# 构建服务
services:
  # 第一个服务拉去jar包
  point:
    # 刚刚打包的镜像
    image: point:latest
    container_name: point
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "7009:7009"
    volumes:
      # 本地文件:映射容器文件
      - "/data/logs/point:/java/log"
      - "/data/linux-job/linux-job/docker-compose/skywalking:/java/skywalking"