version: "3"
# 构建服务
services:
  # 第一个服务拉去jar包
  point:
    image: point:latest
    container_name: point
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "19999:19999"
    volumes:
      # 本地文件:映射容器文件
      - "/data/logs/point:/java/log"
      - "/data/linux-job/linux-job/docker-compose/elk+skywalking/agent/:/java/skywalking"