version: "3"
# 构建服务
services:
  # 第一个服务拉去jar包
  xxljob:
    # 刚刚打包的镜像
    image: blade-xxljob-admin:latest
    container_name: blade-xxljob-admin
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms1024m -Xmx1024m -Xmn256m -Xss256k -Dspring.cloud.nacos.discovery.server-addr=192.168.152.128:8848 -Dspring.cloud.nacos.config.server-addr=192.168.152.128:8848 -Dspring.cloud.nacos.config.namespace=0189e68b-f0d6-4879-a568-a303a42648d2 -Dspring.cloud.nacos.discovery.namespace=0189e68b-f0d6-4879-a568-a303a42648d2
    ports:
      - "7009:7009"
    #volumes:
      # 本地文件:映射容器文件
      - "./volumes/data:/blade/data/applogs/xxl-job"