version: '3'

services:
  nexus:
    image: 'sonatype/nexus3'
    container_name: 'nexus'
    ports:
      - '8081:8081'
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /data/volumes/nexus/nexus-data:/nexus-data
