version: "3"
services:
  redis:
    privileged: true
    restart: always
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - /data/volumes/redis6379/redis:/data
    command:
      # 执行的命令
      # redis-server --appendonly yes
      redis-server --requirepass VtU8XAd --appendonly yes
    #networks:
    #  - vlan-redis
#networks:
#  vlan-redis:
#    external: true