
# 1.设置舆情系统web访问端口，默认端口号8084
server:
  port: 8084
  servlet:
      session:
        cookie:
          name: local-portal
          max-age: -1
        timeout: 7200
          
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  session:
    store-type: redis
    redis:
      namespace: stonedt-portal
  http:
  # 设置编码
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  devtools:
      restart:
        enabled: true #热部署生效
  application:
    name: stonedt-portal
  
  # 2.修改设置MySQL服务器地址和用户名及密码
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://mysql8:3306/stonedt_portal?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: VtU8XAd28UZd4xZBYMJUtbDFdK5ssgUc


 # 3.修改设置Redis服务器地址
  redis:
    database: 0
    host: redis
    port: 6379
    password: VtU8XAd
    max-active: 10000
    max-idle: 10
    max-wait: 100000
    timeout: 100000

  # flyway 自动建库建表设置
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

          
mybatis:
    type-aliases-package: com.stonedt.intelligence.entity
    mapper-locations: classpath:mapper/*.xml
    type-handlers-package: com.stonedt.intelligence.dao.handler

logging:
  level:
     com.stonedt.intelligence.dao : info
kaptcha:
  border: "yes"
  border.color: 105,179,90
  textproducer:
    font:
      color: blue
      size: 40
      names: 宋体,楷体,微软雅黑
    char:
      length: 5
  image:
    width: 150
    height: 50
  session:
    key: code

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
  packagesToScan: com.stonedt.intelligence.api

knife4j:
  # 开启增强配置
  enable: true
  basic:
    enable: true
    # Basic认证用户名
    username: test
    # Basic认证密码
    password: 123
