version: '3.1'
networks:
  kafka-net:
    driver: bridge
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.8.0
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-net
    volumes:
      - /data/volumes/kafka/zookeeper_data:/bitnami/zookeeper
  kafka-0:
    container_name: kafka-0
    hostname: kafka-0
    image: bitnami/kafka:3.2
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_BROKER_ID: "0"
      KAFKA_ENABLE_KRAFT: "no" # 是否启用KRaft
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_LISTENERS: "INTERNAL://:9092,EXTERNAL://0.0.0.0:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka-0:9092,EXTERNAL://主机ip:9093"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_HEAP_OPTS: "-Xms521M -Xmx521M"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: "30000"
    networks:
      - kafka-net
    volumes:
      - /data/volumes/kafka/kafka_0_data:/bitnami/kafka
    depends_on:
      - zookeeper
  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    ports:
      - "9000:8080"
    environment:
      AKHQ_SERVERS: "kafka-0:9092"
      AKHQ_ZOOKEEPER: "zookeeper:2181"
    volumes:
      - /data/volumes/kafka/akhq-application.yaml:/app/application.yml
    networks:
      - kafka-net