version: '3'
services:
  mysql5.7:
    image: mysql:5.7.39-debian
    restart: always
    container_name: mysql5.7
    environment:
      MYSQL_ROOT_PASSWORD: VtU8XAd28UZd4xZBYMJUtbDFdK5ssgUc
    command:
     # --default-authentication-plugin=caching_sha2_password
     --character-set-server=utf8mb4
     --collation-server=utf8mb4_general_ci
     # --explicit_defaults_for_timestamp=true
     # --lower_case_table_names=1
     # --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
     # --skip-name-resolve
    ports:
      - 3307:3307
    volumes:
      - /data/volumes/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /data/volumes/conf.d/mysql.conf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - vlan-mysql
networks:
  vlan-mysql:
    external: true
