version: '3'

services:
  rabbitmq:
    # 别人的阿里云镜像仓库
    image: ccr.ccs.tencentyun.com/wajika/rabbitmq-management:3.7.8
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
