filebeat.inputs:
  # 一台机器上部署多个应用服务，1个filebeat收集这些应用服务的日志
  # type对应一个应用服务，并填写 `fields.source`来标识是哪个服务
  - type: log
    enabled: true
    paths:
      - /logs/point/*.log
    ignore_older: 24h
    clean_inactive: 36h
    # fields:  #定义的自定义字段，给logstash使用
    #   serviceName: point # 对应的应用名
    #   host: 192.168.152.129 #所在ip
output.logstash:
  # The Logstash hosts
  hosts: ["logstash:4560"]